### ISSUE TITLE
Add support for files from classpath

### ISSUE THREAD

**Issue by mitchelkuijpers** [funcool/catacumba#23]
Hi I would like to server my assets from classpath I went into the documentation of ratpack and I found this: http://ratpack.io/manual/current/launching.html#base_dir

This basically means if you want to serve assets from the classpath you need to create a markerfile ```.ratpack``` and catacumba should call http://ratpack.io/manual/current/api/ratpack/server/ServerConfig.html#findBaseDir-java.lang.String- when you don't set a basedir (Or maybe this should be an option?). Would you like a pull request with this change?

**Comment by niwinz** [comment]
Hi @mitchelkuijpers 
Yeah, it would be a great improvement. PR is welcome.

The only thing is that I don't know the best approach for handling this at this moment. Maybe a reasonable option will be if base-dir is not provided, find the `.catacumba` markfile (instead of `.ratpack`). And additionally add an option for specify the default markfile name with the default value to `.catacumba` ?

Thanks!

**Comment by mitchelkuijpers** [comment]
Yeah a ```.catacumba``` markfile would be a much nicer approach no need to expose ratpack internals. The only thing is it does not seem to work correctly for example it does not resolve compiled files from target/public but it does from resources/public (where I put the .ratpack file) :( Maybe it might be a better idea to create a resources middleware like the one from ring? I am just blurting out ideas.

**Comment by niwinz** [comment]
hmm, I'm not pretty sure about take a own solution, the ratpack approach should work fine.  Maybe you should add target/public to `:resources-paths` for make it available to the classpath?

**Comment by mitchelkuijpers** [comment]
Agree would not like that either, the thing is target should be on the classpath since that is the classpath, will investigate further tonight..

**Comment by mitchelkuijpers** [comment]
It seems my problem with loading files from the classpath is related to boot and how ratpack finds assets 
* It get's the current classloader
* finds the markerfile from the classpath
* finds the containing directory and then uses that as a basedir

This is absolutely fine with leiningen (I think?) but not with boot they do some magic and then the basedir resolves to stuff like this ```/Users/mitkuijp/.boot/cache/tmp/Users/mitkuijp/Development/relations_for_jira/ixx/9553b``` This is easily fixed for me with a check if it's dev and then use the ```target``` folder (which is basically the classpath with boot) and otherwise the marker thingy.

I will create a pull request tomorrow that searches for the ```.catacumba``` markerfile by default when no basedir is defined and update the docs accordingly.

**Comment by niwinz** [comment]
Great! I'm looking forward your PR!

**Comment by mitchelkuijpers** [comment]
Going to take a bit longer gonna be busier today then expected. 

One thing is if you don't have markerfile it will throw a runtime exception when starting the server I don't think this is wanted behaviour as a default. So maybe I should add it as a separate option. Still thinking about a name ik think findBaseDir is a pretty name for this, any ideas?

**Comment by niwinz** [comment]
Hmm, I think, that the decided behavior is a proper. And the underlying platform does not works in a exactly way we should workaround. In other words, I don't want condition a design of catacumba by design decisions by the underlying platform unless there is no other remedy or that the change is reasonable.

And for this case, maybe a better approach will be catch that runtime exception and simple ignore it. This approach maintains backward compatibility (it is not very important point in this phase of development but is not bad...) and behaves as we expect. So if no file is found no base-dir is set.

What do you think?

**Comment by niwinz** [comment]
Done in master.
